### ISSUE TITLE
Item names and descriptions get messed up after opening Mod Options menu in settings.

### ISSUE THREAD

**Issue by 4AC11** [Bubbet/BubbetsItems#1]
I could've sworn I already posted something here about this problem, but I guess not? Regardless...

I was at first extremely confused as to why the names were getting messed up sometimes and other times weren't, until I realized that going into settings and specifically the Mod Options menu added by Risk of Options causes the item names to bug out. This only fixes itself when restarting the game, and breaks again immediately upon accessing the options menu.
![image](https://github.com/Bubbet/BubbetsItems/assets/97819008/916b4c49-0757-4972-9aa1-506bb7bf4b1d)
Example of an item's name and description being messed up.
It also seems to affect other things in the mod's config itself, but given that accessing said config is causing the bug I have no idea whether this is just how the config is supposed to be. 
![image](https://github.com/Bubbet/BubbetsItems/assets/97819008/037b2c6e-bc8a-45fe-bfa9-0174f0541231)
Example of (maybe?) bugged config descriptions

This has been an issue for a long time and it's really quite a pain to have to keep the Thunderstore page open just to see the item descriptions.

**Comment by 4AC11** [comment]
update: also affects these
![image](https://github.com/Bubbet/BubbetsItems/assets/97819008/6a0d22c7-a884-48d2-9171-87274f9e601e)
![image](https://github.com/Bubbet/BubbetsItems/assets/97819008/0b111fc8-0969-4f86-a5c4-70905f129f01)

**Comment by 4AC11** [comment]
Hey, saw that the mod updated but this doesn't seem to have been fixed. Any progress on this??

**Comment by Bubbet** [comment]
I have no idea what's causing this it's some cross mod compatibility issue.
I've done like everything in my power to fix it from my end without knowing
what's causing it.

**Comment by acanthii** [comment]
Seems to only happen with MoonstormSharedUtils installed (dependency of Starstorm2)
Would love to see this issue fixed either on this side or theirs ;)

**Comment by Teadoo** [comment]
Not sure why MoonstormSharedUtils causes this issue but I found success in moving my mods in r2modman in a way that BubbetsItems loads before MSU, seems to have fixed the issue.
![image](https://github.com/user-attachments/assets/6e051067-bf47-4fce-ac4c-e00e8a6eb30e)

**Comment by acanthii** [comment]
Issue still persists with MSU 2.0 sadly :(
