### ISSUE TITLE
Void fields can't be completed.

### ISSUE THREAD

**Issue by MPMConstellation** [Bubbet/BubbetsItems#3]
The first void cell can be started, and spawns enemies, but after it's completed, no item drop spawns, enemies continue spawning, and no new void cell can be started.
[LogOutput.log](https://github.com/user-attachments/files/15754379/LogOutput.log)

**Comment by Bubbet** [comment]
Looks like they might have changed the method signature for pickup
droplets. Probably just needs to be recompiled. Thanks for the info.

**Comment by Darkmega18** [comment]
the void cell also gets stuck at 99%.
would you be able to patch it, bubbet? :< or try the re-compile then update it?

**Comment by Bubbet** [comment]
should be fixed now

**Comment by Darkmega18** [comment]
oh my~
thanks.
also before this I had discovered installing "GoxofBears" allowed the void fields to progress just fine. but then I stopped playing for a bit. :V
