### ISSUE TITLE
Recursion Bullets math is wrong

### ISSUE THREAD

**Issue by bobot-dev** [Bubbet/BubbetsItems#4]
Recursion Bullets runs the code
"args.attackSpeedMultAdd += 1f + buffAmount * recursionBullets.scalingInfos[0].ScalingFunction(amount);"
which leads to them giving a flat +1 attackspeed when picked up

**Comment by Bubbet** [comment]
Good catch, must have slipped by when porting to r2api instead of running
my own stuff.
