### ISSUE TITLE
Void Lunars all locked when using Command Artifact 

### ISSUE THREAD

**Issue by NoxNap** [Bubbet/BubbetsItems#7]
👋 hello, when using the command artifact it seems all the void lunars are locked when you open them. I initially thought maybe you had to unlock them but can't find any docs stating how to or whether that's intentional; couldn't find any FAQ that answered this either and nothing in settings indicated it was intentional to have them locked. 

If you can clarify whether the void lunars should be locked when using the command artifact (and how to unlock them) that'd be greatly appreciated!

**Comment by Bubbet** [comment]
Do you have the survivors of the void dlc? They're usually obtained at a
shop by the portal at the bottom of the bazaar

**Comment by NoxNap** [comment]
> Do you have the survivors of the void dlc? They're usually obtained at a
> shop by the portal at the bottom of the bazaar

Yes, when I go down there and open one up all of them are locked. I kind of believe it may be due to command artifact being used but never tested without command artifact being used. They're all locked as if I need to complete an achievement.

**Comment by Bubbet** [comment]
That's real weird, the only unlock condition on them should be the
expansion which to enable requires sotv
