### ISSUE TITLE
gyroscopic whisk

### ISSUE THREAD

**Issue by ShapiroDeluxe** [Bubbet/BubbetsItems#8]
haha. heyyy so i was wondering. haha. why isnt gyroscopic whisk on the ai blacklist? ha. haha.

https://github.com/user-attachments/assets/b8a0d06b-a773-4787-9b77-6ab5ddb46618

(i am salty but this is hilarious. mostly sharing this because it's funny but please do change this)

**Comment by Bubbet** [comment]
Because it's funny. Iirc there's a config for it but I kept it how it is
because funny
