### ISSUE TITLE
Logbook Issues

### ISSUE THREAD

**Issue by smalllbuddy** [Bubbet/BubbetsItems#9]
SOTS changed the display of models in the logbook (black background similar to enemy displays, no purple floor). This mod has not been updated accordingly. Additionally names and descriptions are either bugged or empty.
![image](https://github.com/user-attachments/assets/8340fd73-dd62-42a5-8786-a7cd7c0c323e)

**Comment by Bubbet** [comment]
This is an issue with msu no? It works fine by itself?

**Comment by smalllbuddy** [comment]
I'm not sure what has changed, but the name/descriptions are now functioning. Doesn't seem to be an issue with msu as Starstorm 2 doesn't have this issue with the models. Also not sure if there is meant to be info under 'notes' but if not it would at least be nice to have some filler BS that matched vanilla items such as data scraper or just shipping info.
![image](https://github.com/user-attachments/assets/200db1af-a6c8-44cc-b005-2294bc2dd1ed)

**Comment by Bubbet** [comment]
It's still msu, it just happens after opening risk of options.
